env:
  browser: true
  es6: true
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
rules: 
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  quotes: 
    - error
    - single
  jsx-quotes:
    - error
    - prefer-single
