export enum NOTE_DURATION {
    whole = 'whole',
    half = 'half',
    quarter = 'quarter',
    eighth = 'eighth',
    sixteenth = 'sixteenth',
}

export enum NOTE_DURATION_NUMBER {
    whole = 4,
    half = 2,
    quarter = 1,
    eighth = 0.5,
    sixteenth = 0.25,
}

export enum NOTE_PITCH {
    C1 = 'C1',
    D1 = 'D1',
    E1 = 'E1',
    F1 = 'F1',
    G1 = 'G1',
    A1 = 'A1',
    B1 = 'B1',
    C2 = 'C2',
    D2 = 'D2',
    E2 = 'E2',
    F2 = 'F2',
    G2 = 'G2',
    A2 = 'A2',
    B2 = 'B2',
    C3 = 'C3',
    D3 = 'D3',
    E3 = 'E3',
    F3 = 'F3',
    G3 = 'G3',
    A3 = 'A3',
    B3 = 'B3',
    C4 = 'C4',
    D4 = 'D4',
    E4 = 'E4',
    F4 = 'F4',
    G4 = 'G4',
    A4 = 'A4',
    B4 = 'B4',
    C5 = 'C5',
    D5 = 'D5',
    E5 = 'E5',
    F5 = 'F5',
    G5 = 'G5',
    A5 = 'A5',
    B5 = 'B5',
    C6 = 'C6',
    D6 = 'D6',
    E6 = 'E6',
    F6 = 'F6',
    G6 = 'G6',
    A6 = 'A6',
    B6 = 'B6',
}